export const SAVE_FILM = 'SAVE_FILM'
export const SAVE_FILM_SUCCESS = 'SAVE_FILM_SUCCESS'
export const SAVE_FILM_FAIL = 'SAVE_FILM_FAIL'

export const UPDATE_FILM = 'UPDATE_FILM'
export const UPDATE_FILM_SUCCESS = 'UPDATE_FILM_SUCCESS'
export const UPDATE_FILM_FAIL = 'UPDATE_FILM_FAIL'
